### ISSUE TITLE
Inline keyboard parameters

### ISSUE THREAD

**Issue by mad-ady** [foxcris/appdaemon-telegrambot#11]
I've extracted the code you're using to create an inline keyboard and call it to create a custom keyboard for my needs. Here is the code, by the way if you want to refactor your work:

```
    def _build_keyboard_answer(self, items, target_id):
        """ items: list of dictionaries in the form [{'description':'', 'url':''}]
        """
        keyboard = list()
        keyboardrow = list()
        keyboard_width = 8
        count = 1
        msg = "";

        for item in items:
            keyboardrow.append((count, item['url']))
            msg += f"{count}: {item['description']}\n"
            count+=1
            if count % keyboard_width == 0:
                keyboard.append(keyboardrow)
                keyboardrow = list()
        
        if len(keyboardrow) > 0:
            keyboard.append(keyboardrow)
        
        self._log_debug(msg)
        self._log_debug(keyboard)
        self.call_service(
            'telegram_bot/send_message',
            target=target_id,
            message=self._escape_markdown(msg),
            inline_keyboard=keyboard)
```

Here's how I build it and use it:
```
            #prepare options
            keyboard_options = []
            for media_player in media_players:
                for fmt in self._latest_media:
                    keyboard_options.append({
                        'description': f"Play format {fmt} to {media_player['friendly_name']}", 
                        'url':f"/play_media?entity_id={media_player['entity_id']};fmt_id={fmt}"})
            self._build_keyboard_answer(keyboard_options, user_id)
```
I see that your callback handling code parses parameters split by `;`:
```
params = dict(item.split("=") for item in params.split(";"))
```

However, something strange happens. When I build a keyboard with two parameters, like above, everything seems fine in the logs, but the keyboard never appears on my phone:
```
2020-05-09 16:46:11.844529 INFO TelegramBot: DEBUG: TelegramBot: _build_keyboard_answer: [[(1, '/play_media?entity_id=media_player.tv_bedroom_android;fmt_id=140'), (2, '/play_media?entity_id=media_player.tv_living_atv;fmt_id=140'), (3, '/play_media?entity_id=media_player.tv_bedroom_atv;fmt_id=140')]]

```
If I remove the `;fmt_id={fmt}` part from the `url`, then the keyboard shows up fine.
Any idea what's going on? I kind of need to send two parameters, though if not possible I can find other ways...

**Comment by foxcris** [comment]
Hmm, i rember implementing the possibility to use multiple parameters, but i am not sure if i ever used it, sorry.
Perhaps its a problem due to using multiple equal characters ("=")?  For the inline_keyboard we do not use an escape_function currently. Perhaps we need one, take a look here: https://core.telegram.org/bots/api#markdownv2-style

> * Any character between 1 and 126 inclusively can be escaped anywhere with a preceding '\\' character, in which case it is treated as an ordinary character and not a part of the markup.
> * Inside pre and code entities, all '`‘ and ’\\‘ characters must be escaped with a preceding ’\\' character.
> * Inside (...) part of inline link definition, all ')‘ and ’\\‘ must be escaped with a preceding ’\\' character.
> * In all other places characters '_‘, ’*‘, ’[‘, ’]‘, ’(‘, ’)‘, ’~‘, ’`‘, ’>‘, ’#‘, ’+‘, ’-‘, ’=‘, ’|‘, ’{‘, ’}‘, ’.‘, ’!‘ must be escaped with the preceding character ’\\'.
> * In case of ambiguity between italic and underline entities __ is always greadily treated from left to right as beginning or end of underline entity, so instead of ___italic underline___ use ___italic underline_\r__, where \r is a character with code 13, which will be ignored.

**Comment by foxcris** [comment]
Refactor the keyboard creation is a good idea. I think i will borrow your code :-)

**Comment by avico78** [comment]
for learning and get better understand of the app ...
I'm trying to make help menu send with key_board,
using same approach @foxcris  did.

done as following:
```
 keyboard = list()
        keyboardrow = list()
        count = 0
        if command == "/help":
            msg = "The following commands are available:\n/help: This help\n"
            for command in self._commanddict:
                method_str = f'{command}'
                desc = self._commanddict.get(command).get("desc")
                msg += f"{command} : {desc}\n"
                count += 1
                keyboardrow.append((desc,{method_str}))
                if count % 3 == 0:
                        keyboard.append(keyboardrow)
                        keyboardrow = list()
            if len(keyboardrow) > 0:
                  keyboard.append(keyboardrow)           
            self.log(f"Telegram Command:\n\n\n: {keyboard} \n\n\n\n")
            self.call_service(
                'telegram_bot/send_message',
                target=user_id,
                message=self._escape_markdown(msg),
                inline_keyboard=keyboard)

```
I also added in entry in  self._callbackdict
with 
```
 "/state_light": {"desc": "State of light", "method": self._cmd_state_light},
```
First screen working , but when nothing happened when i click on the "state_light" button...
would appreciate your help

**Comment by foxcris** [comment]
@avico78 : I hust implemented this while i was doing some refactoring. Give me some more time, i will just update the unit tests and then push everything to the repo.

Regarding your solution: 
Nothing happens because your are using a callback! Not a command. Telegram distinguishes between those two types of messages for a bot.
Within my app `_receive_telegram_callback` handles all callbacks and `_receive_telegram_command` all commands. As you are now sending callbacks you have to extend `_receive_telegram_callback` like i have done it:
```
if callback in self._commanddict:
            method = self._commanddict.get(callback).get('method')
            method(target_id=callback_id)
            #https://python-telegram-bot.readthedocs.io/en/stable/telegram.callbackquery.html
            #After the user presses an inline button, Telegram clients will display a progress 
            #bar until you call answer. It is, therefore, necessary to react by calling 
            #telegram.Bot.answer_callback_query even if no notification to the user is needed 
            #(e.g., without specifying any of the optional parameters).
            self.call_service(
                'telegram_bot/answer_callback_query',
                message="",
                callback_query_id=callback_id)
```
But I also hat to rename all callback to resolve conflicting names with commands and callbacks as all commands could now also be used as callbacks.

**Comment by mad-ady** [comment]
> Hmm, i rember implementing the possibility to use multiple parameters, but i am not sure if i ever used it, sorry.
> Perhaps its a problem due to using multiple equal characters ("=")? For the inline_keyboard we do not use an escape_function currently. Perhaps we need one, take a look here: https://core.telegram.org/bots/api#markdownv2-style
> 
> > * Any character between 1 and 126 inclusively can be escaped anywhere with a preceding '\' character, in which case it is treated as an ordinary character and not a part of the markup.
> > * Inside pre and code entities, all '`‘ and ’\‘ characters must be escaped with a preceding ’\' character.
> > * Inside (...) part of inline link definition, all ')‘ and ’\‘ must be escaped with a preceding ’\' character.
> > * In all other places characters '_‘, ’*‘, ’[‘, ’]‘, ’(‘, ’)‘, ’~‘, ’`‘, ’>‘, ’#‘, ’+‘, ’-‘, ’=‘, ’|‘, ’{‘, ’}‘, ’.‘, ’!‘ must be escaped with the preceding character ’\'.
> > * In case of ambiguity between italic and underline entities __ is always greadily treated from left to right as beginning or end of underline entity, so instead of _**italic underline**_ use **_italic underline_\r**, where \r is a character with code 13, which will be ignored.

Ok, I tried several variants - using _ instead of ; as a delimiter, using : instead of = in the second parameter, and calling _escape_markdown() on the whole url, and none of them allowed me to pass the second parameter and get a keyboard popup. Once I delete the second parameter, the keyboard happily shows up.
Weird. I may need to read on Telegram's keyboard documentation...

**Comment by foxcris** [comment]
i think i got it. Just had this problem during implementing https://github.com/foxcris/appdaemon-telegrambot/issues/7.
In https://core.telegram.org/bots/api it is stated:
![grafik](https://user-images.githubusercontent.com/361299/81611556-8d8a6680-93db-11ea-926c-cc05f8c54274.png)
-> we have only 64bytes for callbacks. This is nearly completly used with one callback and the md5 entity hash.

**Comment by mad-ady** [comment]
I thought you were passing url, not callback_data when I looked over the
code. Might be a problem with long entity names too.

In this case callbacks should encode the entity name in a standard way. If
you build a dictionary of sorted entity names when you connect to HA and
assign to them a numeric (or hex, or ascii) id and keep the reversed
dictionary too, it will work, but you won't handle the case where the user
(or system) creates new entities on the fly without HA restart (I think
it's possible with new integration discovery wizards). So it will require
module restarts after HA changes (or periodic refreshes, but with a flag
that prevents the refresh between a request/callback).

Let me know what you think

Regards,
Adrian

**Comment by foxcris** [comment]
I use url or callback this depends on the use case. 

Your analysis is right, building a dictionary and assign each entity a simple numeric id would be possible but we would have to address changes of the entities during runtime. Question is: how often are entities created/deleted during runtime? Is this really a usecase we have to address? 

An other possibility would be to use an hash algorithm with shorter hashvalues (currently i use md5 hashes) and also use ids to identify the function to call not the name.

**Comment by mad-ady** [comment]
Question is: how often are entities created/deleted during runtime? Is this
really a usecase we have to address?

I think so, yes. HA is slowly moving configuration of its components to the
webend, instead of through yaml + restart. Maybe it emmits some event you
can listen to when a new entity is created (doesn't look like it yet:
https://www.home-assistant.io/docs/configuration/events/)

A shorter hash sounds great. It wouldn't mess with existing objects.
Something like the first x characters of the sha1 hash, like git uses?
https://stackoverflow.com/questions/16413373/git-get-short-hash-from-regular-hash
You could keep a dictionary of short hashes - entity mappings for quick
lookup.
