### ISSUE TITLE
Enhancement: Telegram app print HA log

### ISSUE THREAD

**Issue by avico78** [foxcris/appdaemon-telegrambot#12]
It could  be really useful if we can fetch HA log and present it in telegram ,
User runs something from telegram app and want to see the log from HA ,
(tail last something like last ~20-30 lines )

**Comment by foxcris** [comment]
I just checked the appdaemon documentation and could not find a provided function to get the log from home-assistant. Do you know of such a function?

**Comment by foxcris** [comment]
Home-assistant itself provides a log view in the developer section. I took a look and saw that they used the rest api to get the log: 
https://developers.home-assistant.io/docs/api/rest/#get-apierror_log
Unfortunately only the error logs seems to be available via the rest api.

**Comment by foxcris** [comment]
Added to new commands:
- added command get_log
- added command get_error_log

plesae give it a try and reopen/create a new bug report if you find any errors
