### ISSUE TITLE
Enhancement: Get state of the system

### ISSUE THREAD

**Issue by foxcris** [foxcris/appdaemon-telegrambot#4]
Implement a command (/state_system) to request the current state of the system.

To get the system information the home-assistant integration system-monitor (https://www.home-assistant.io/integrations/systemmonitor/) is used.

**Comment by foxcris** [comment]
Implented with version 1.0

**Comment by avico78** [comment]
Working great ,Tnx!
for extend_system -
Maybe need to make if more flexible so it will display   more all/attributes of  the sensor
user add to extend_system .
