### ISSUE TITLE
Enhancement: Adding an option to trigger automation that is defined in HA

### ISSUE THREAD

**Issue by foxcris** [foxcris/appdaemon-telegrambot#7]
Extracted from https://github.com/foxcris/appdaemon-telegrambot/issues/2

2.Adding an option to trigger automation /scripts/shell_command that define in HA,
in example , user send /automation and by the same approach u fetch all light sensors,
show automations (with an option of filtering as suggest in #1)

**Comment by foxcris** [comment]
@avico78 i have just implemented the following new commands:
* /turnon_automation: Turn on automation
* /turnoff_automation: Turn off automation
* /trigger_automation: Trigger automation
* /state_automation: State of automation

If you have time please give them a try, code is published in the master branch

**Comment by avico78** [comment]
Tested , working great !
love the option for disable/enable automation .

I also added execution of scripts - I done this with  integration we discuss for managing container : 
1.Create SSH key from HA--> Host (one time effort)
2.Create sh script which upgrading container by name 
3.add shell_commands to execute the sh - each command send different container name to sh upgrade sh script.
4.Create HA script which execute the shell_command+ notify telegram once finish

Now i can upgrade any container by simple telegram click with no security worries:)

For script :  

    self._commanddict
```
"/execute_script": {"desc": "Execute script", "method": self._cmd_execute_script}

```
  self._callbackdict
```

```
"/clb_execute_script": {"desc": "Execute Script", "method": self._clb_execute_script}
```

    def _cmd_execute_script(self, target_id):
        msg = "Which script do you want to execute?\n\n"
        statedict = self._get_state_filtered()
        keyboard_options=list()
        for entity in statedict:
            if re.match('^script.*', entity, re.IGNORECASE):
                self._log_debug(statedict.get(entity))
                hashvalue = self._get_hash_from_entityid(entity)
                desc = self._getid(statedict,entity)
                keyboard_options.append({
                    'description': f"{desc}", 
                    'url':f"/clb_execute_script?entity_id={hashvalue}"})
                    
        self._build_keyboard_answer(keyboard_options, target_id, msg)
        
##Scripts

    def _clb_execute_script(self, target_id, paramdict):
        hashvalue = paramdict.get("entity_id")
        entity_id = self._get_entityid_from_hash(hashvalue)
        if entity_id is not None:
            friendly_name = self.get_state(entity_id, attribute="friendly_name")
            msg=f"Execute script {entity_id} ({friendly_name})"
            self._send_message(msg, target_id)
            self.call_service(
                'telegram_bot/answer_callback_query',
                message=self._escape_markdown(msg),
                callback_query_id=target_id)
            self.call_service("script/turn_on",
                              entity_id=entity_id)
        else:
            msg = "Unkown entity. Please do not resent old commands!"
            self._send_message(msg, target_id)
            self.call_service(
                'telegram_bot/answer_callback_query',
                message=self._escape_markdown(msg),
                callback_query_id=target_id,
                show_alert=True)        



```

**Comment by foxcris** [comment]
Thanks for the test! I will clode this issue now.

For your  execution of scripts, will you create an push request for this?
