### ISSUE TITLE
Filtering - not working properly 

### ISSUE THREAD

**Issue by avico78** [foxcris/appdaemon-telegrambot#9]
Seems filtering support a single entity only .
Test:
app.yaml
filter_exclude_light:     "light.dcede305_a5afe582,light.9c9aec1d_a4871501" 
see:
No filtering done 

Suggested solution for support single to multiple filtering entities:

1. All places:
if self.args["<ANY>"] is not None **and** self.args["<AN>"]!="":
should changed to 
if self.args["filter_exclude_vacuum"] is not None **OR** self.args["filter_exclude_vacuum"]!="":

2.all functions using the filter should change to:

original:
if self._filter_exclude_light is not None and re.search(**self._filter_exclude_light , entity**, re.IGNORECASE):

Should be changed to 
 if  self._filter_exclude_light and re.search(**entity,self._filter_exclude_light**,re.IGNORECASE):

**Comment by mad-ady** [comment]
I have a suggestion for filtering. The yaml should have only two main entries:
```
blacklist:
  - media_player
  - light.kitchen
  - sensor.secret
whitelist:
  - person.john_doe
  - automation.do_x
```

If the name in the list doesn't have a dot - it will be considered a "type" (or whatever HA calls them), and all subitems of the same type are blacklisted/whitelisted. If there is a dot, then you can compare the current item in your processing with what is in the list.
It should simplify configuration (there is nothing wrong with mixing types, but the user knows it's a blacklist or a whitelist) and checking can be done by loading the list as a dictionary, testing all items without a dot and comparing them with the current type, and checking all items with a dot against the current item (should be simple). Ideally there should be a function to compare the current item with both lists and return true or false if the item is readable by the plugin.

If the blacklist is empty - nothing is filtered out
If the whitelist is empty - nothing is filtered out
If both the blacklist and whitelist are non-empty, first apply the blacklist and then the whitelist (open for debate).

Regarding exact matching - you could do exact matches (since they are faster), or regex (but may be more confusing for the end user).
Let me know if you need help with it.

**Comment by avico78** [comment]
@mad-ady  ,

Note , the "get state" currently support light,cover,person,climate and guess more thing may added,
Letting the user define whitelist for all will be annoying, 
I think by default it better display all entities leaving the ones mention as excluded .
from the other hand , instead of dedicating excluded list per topic(light,cover )- we can put all in one blacklist .
I believe the impact of the performance will be minor .

**Comment by mad-ady** [comment]
Well, if you leave the whitelist empty it should allow access to all  entities. But there will be (paranoid?) users that will want to allow access only to specific items (and manually blacklisting everything else will be too hard to maintain) - hence the idea of whitelist. Of course, you don't need to use it, but it pays to plan ahead and include it in the code from the start.

**Comment by foxcris** [comment]
@avico78 the filtering is done with regular expressions. It is currently working on my setup. 
From your example
filter_exclude_light: "light.dcede305_a5afe582,light.9c9aec1d_a4871501" 
light.dcede305_a5afe582,light.9c9aec1d_a4871501 -> is not a valid regular expression. You have to change this to (light.dcede305_a5afe582,light.9c9aec1d_a4871501). 
Please try again with a regular expression.

Here a link to regular expressions:
https://docs.python.org/3.7/library/re.html

**Comment by foxcris** [comment]
Regarding your proposal to use a baclklist and whitelist defined in a yaml config:
1. implementing a white an blacklist should be possible with minimal effort. 
Your workflow for handling the blacklist/whitelist is reasonable and a good approach
- If the blacklist is empty - nothing is filtered out
- If the whitelist is empty - nothing is filtered out
- If both the blacklist and whitelist are non-empty, first apply the blacklist and then the whitelist (open for debate). 
2. I am not completly sure if appdaemon support subsections in the app.yaml. But is seems like it (https://appdaemon.readthedocs.io/en/latest/APPGUIDE.html).
However is it really better to let the user definde each entity separatly? Shound we stay with using regular expressions? Perhabs we could use somthing like:
blacklist:
  - regex1
  - regex2
I would use this to compose one overall regex (regex1|regex2). Thus on can use regex or simply define single entities.

**Comment by mad-ady** [comment]
I think it comes down to how you apply the white/black list. I was thinking of loading the items in the list into two dictionaries. 
One would be `integration_category_filter` containing categories such as `light`, or `sensor`, etc. 
The other (`element_filter`) would contain items with a dot, like `cover.bedroom`.
You could then create a function that filters items, like this (not tested!):
```
def apply_filter(self, items):
   filtered_items = []
   for item in items:
     category = item.split(".")[0]
     if category not in integration_category_filter:
        if item not in element_filter:
           filtered_items.append(item)
    return filtered_items
```
You can then call this in each function:
```
def _cmd_state_cover(self, target_id):
  statedict = self.apply_filter(self.get_state())
```
and you would end up with a filtered list that you can process as usual.

It's faster to use dictionaries (you just test if item is in dictionary) then using regex. I understand the power of regexes - but there's also a performance overhead (it should not matter in this case), but I too have suffered from overusing regexes for every problem (I come from a perl background). 
But you're right - this implementation would not use regex at all. Not sure what is best - it's up to you to decide. Either way - the yaml configuration should be the same, even if the implementation of filtering is different.

**Comment by foxcris** [comment]
Implemented in [v1.1](https://github.com/foxcris/appdaemon-telegrambot/releases/tag/v1.1).
Please give it a try and report back any new issues.

**Comment by avico78** [comment]
tested on v1.1 
working great

**Comment by avico78** [comment]
+ @mad-ady

**Comment by mad-ady** [comment]
I'll try to have a look and test it out, but I'm currently low on free time :(
Usually a whitelist means items are not filtered, even if there is a blacklist that explicitly filters the group or the item. The designer needs to choose which gets tested first - the whitelist or the blacklist. It could work either way, but we need to chose the best/most helpful approach (and the easiest implementation).

**Comment by avico78** [comment]
> I'll try to have a look and test it out, but I'm currently low on free time :(
> Usually a whitelist means items are not filtered, even if there is a blacklist that explicitly filters the group or the item. The designer needs to choose which gets tested first - the whitelist or the blacklist. It could work either way, but we need to chose the best/most helpful approach (and the easiest implementation).

Right , the thing is the app works with different entities types ,
So as u said whitelist mean items are not being filtered ...
so it more reasonable to make filtering by entity type .
meaning keep one whitelist parameter as we have now,
but the filtering mechanism should be smarter so if i put whitelist for one automation/script,
it doesn't mean I want to filter person/light and so on....

**Comment by mad-ady** [comment]
I think the implementation will be simpler once we clarify how it's
supposed to work with some examples. Let's assume this configuration:
```
whitelist:
 - light
 - sensor
 - automation.do_x
 - automation.do_t
blacklist:
 - media_player
 - light.dungeon
 - automation.do_y
 - automation.do_t
```

What should happen for the following inputs (truth table)?
```
light.blue -> allow
light.dungeon -> deny
sensor.temperature -> allow
media_player.chromecast -> deny
automation.do_x -> allow
automation.do_y -> deny
automation.do_z -> allow/based on default policy?
automation.do_t -> conflicting rules... -> allow based on default policy?
camera.dungeon -> allow/based on default policy?
```
So, some combinations are ambiguous or conflicting, and it seems we need a
default policy to allow/deny stuff based on user preference.
